### ISSUE TITLE
[BUG] Trakt not working in Seren 2.1.4

### ISSUE THREAD

**Issue by ASmanaTH** [nixgates/plugin.video.seren#682]
No watched movies or shows are marked as such, it's simply as if Trakt isn't configured at all. This reproduces with Seren 2.1.4 with LibreELEC 10 final on RPi4 but I think it happened with at least one previous Seren version as well. In short, upon LE boot the log says:

`'TraktAPI' object has no attribute 'session'`

Also, when attempting to authorize Trakt from the settings menu, nothing happens. No dialog pops up, the settings menu simply closes. Log says:

```
INFO <general>: SEREN (-1): Seren, Running Path - {'action': 'authTrakt'}
ERROR <general>: SEREN (-1): Failure to copy to clipboard, 
                                                   [Errno 2] No such file or directory: 'xsel'
```

Full debug log [here](https://github.com/nixgates/plugin.video.seren/files/7079064/kodi.zip).

**Comment by drinfernoo** [comment]
That last bit seems similar to me to #667, but I haven't gotten to look too closely yet.

**Comment by ASmanaTH** [comment]
> That last bit seems similar to me to #667, but I haven't gotten to look too closely yet.

In fact, I was also using LE 9 until a few days ago when LE 10 final was released. In LE 9 there's a quickly disappearing authorization dialog, I was able to catch it using slow motion on my phone (lol). In LE 10 there's nothing, not even the quickly disappearing dialog.

**Comment by drinfernoo** [comment]
Can you try revoking Trakt first *before* trying to reauthorize?

**Comment by ASmanaTH** [comment]
I revoked and then re-authorized Trakt and everything seems to be working fine so far.

**Comment by drinfernoo** [comment]
We should have this fixed for the next update 👍

**Comment by drinfernoo** [comment]
This should be fixed in 2.1.5, can you check?

**Comment by gn77b** [comment]
I tested with one movie in 2.1.5 and it's working.

**Comment by drinfernoo** [comment]
@ASmanaTH, can you confirm?

**Comment by ASmanaTH** [comment]
Working in 2.1.5
